Se creo el modal para el perfil del usuario
0aps/art-marketplace pull request #5
Opened 2022-01-08 21:27 UTC by JoseJuanM

Solo falta el PUT al editar la informacion del usuario

2022-01-10 03:47 UTC, 0aps commented
@JoseJuanM couple of items to check:

1. Write the commit message in english and follow [these guidelines](https://cbea.ms/git-commit/).
2. Fix merge conflicts

2022-01-10 03:48 UTC, 0aps commented on microservices/frontend/src/components/app/App.js
> +  const onTrigger = (event) => {
there's no need to do this on the App components We should handle this as part of the App reducer. (the state to display or not the modal)

2022-01-10 03:51 UTC, 0aps requested changes

2022-01-10 03:51 UTC, 0aps commented on microservices/frontend/src/components/navbar/NavBar.js
> +        <button name="myname" onClick={onTrigger}>
We should remove this and handle it directly on the profile component.

2022-01-10 03:51 UTC, 0aps commented on microservices/frontend/src/components/profile-modal/ProfileModal.js
> +const Contenido = styled.div`
Change the name of the component to english

2022-01-16 17:58 UTC, JoseJuanM reviewed
Ok, I will make the changes

2022-01-17 02:20 UTC, 0aps commented
Please resolve merge conflicts on your branch (i.e pull from main on this repository) @JoseJuanM

2022-01-17 21:08 UTC, 0aps commented on microservices/frontend/src/components/app/App.js
> +          <Header user={user} logout={logout} showModal={showModal} handleOpen={handleOpen} handleClose={handleClose}/>
We probably can improve here but let's merge and solve it later.

2022-01-17 21:09 UTC, merged